### ISSUE TITLE
Getting Error on Github Login

### ISSUE THREAD

**Issue by jaanisfehling** [freckle/yesod-auth-oauth2#180]
**[Error] FetchCredsYesodOAuth2Exception (JSONDecodingError "github" "Error in $.id: parsing Text failed, expected String, but encountered Number")**

Maybe this occurs because I was already logged in once.

**Comment by pbrisbin** [comment]
Can you please provide some more details about the version your using, and show the code you use to integrate it?

The [current code in this library](https://github.com/freckle/yesod-auth-oauth2/blob/11948a65c405f1a99ccb327d328d416e492542a1/src/Yesod/Auth/OAuth2/GitHub.hs#L18-L21) uses:

```hs
newtype User = User Int

instance FromJSON User where
  parseJSON = withObject "User" $ \o -> User <$> o .: "id"
```

This means our JSON parser is expecting a number as `.id`, so the only way I can imagine you are getting **Error in $.id: parsing Text failed, expected String, but encountered Number* is if you are using your own (broken) type and parser for the user response.

**Comment by jaanisfehling** [comment]
My code (I just replaced `authOAuth2` with `authOAuth2Widget`):

```
newtype User = User Text

instance FromJSON User where
    parseJSON = withObject "User" $ \o -> User <$> o .: "id"


oauth2GitHubScoped :: YesodAuth m => [Text] -> Text -> Text -> AuthPlugin m
oauth2GitHubScoped scopes clientId clientSecret =
  authOAuth2Widget githubWidget "github" oauth2 $ \manager token -> do
    (User userId, userResponse) <-
      authGetProfile
        "github"
        manager
        token
        "https://api.github.com/user"

    pure
      Creds
        { credsPlugin = "github"
        , credsIdent = T.pack $ show userId
        , credsExtra = setExtra token userResponse
        }
 where
  oauth2 =
    OAuth2
      { oauth2ClientId = clientId
      , oauth2ClientSecret = Just clientSecret
      , oauth2AuthorizeEndpoint =
          "https://github.com/login/oauth/authorize"
            `withQuery` [scopeParam "," scopes]
      , oauth2TokenEndpoint = "https://github.com/login/oauth/access_token"
      , oauth2RedirectUri = Nothing
      }

```

**Comment by pbrisbin** [comment]
You have there `newtype User = User Text`.

It makes sense you are getting the error, `parsing Text failed, expected String, but encountered Number`.

You should fix your code to match the what we do, which is `newtype User = User Int`.

**Comment by jaanisfehling** [comment]
Ohhh, thank you. I guess missed that when I copied over the code from the Google plugin. If you want, I can open a PR to add a `oauth2GitHubScopedWidget`.

**Comment by pbrisbin** [comment]
> If you want, I can open a PR to add a oauth2GitHubScopedWidget

Totally up to you. I'd accept it.
